CREATE TABLE IF NOT EXISTS tbl_campaign (
  campaign_id INT PRIMARY KEY AUTO_INCREMENT,
  fund_name VARCHAR(255) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  goal_amount DECIMAL(12,2) NOT NULL,
  message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);